#!/usr/bin/env bash
# Generated by generate.py -- do not edit; edit the data files and regenerate.
#
# 15 patches that are written and rebased but never opened upstream.
# Dry run by default. Review the diffstat each one prints, then:
#     SUBMIT=1 ./submit-unsent.sh            # all of them
#     SUBMIT=1 ./submit-unsent.sh llama.cpp  # just the forks you name
set -uo pipefail

SUBMIT="${SUBMIT:-0}"
ONLY=("$@")

# gh is only needed to actually open a pull request; a dry run just reads branches.
if [ "$SUBMIT" = 1 ]; then
  command -v gh >/dev/null || { echo 'need the gh CLI to submit' >&2; exit 1; }
  gh auth status >/dev/null 2>&1 || { echo 'gh not authenticated: gh auth login' >&2; exit 1; }
fi

wanted() {
  [ "${#ONLY[@]}" -eq 0 ] && return 0
  for p in "${ONLY[@]}"; do [ "$p" = "$1" ] && return 0; done
  return 1
}

submit() { # fork branch upstream base title body
  local fork="$1" branch="$2" up="$3" base="$4" title="$5" body="$6"
  wanted "$fork" || return 0
  echo "=== $up  <-  azrabano23:$fork@$branch  (base: $base)"
  echo "    $title"
  git ls-remote --exit-code --heads "https://github.com/azrabano23/$fork" "$branch" \
    >/dev/null 2>&1 || { echo "    SKIP: branch is gone from the fork"; return 0; }
  local tmp; tmp="$(mktemp -d)"
  if git -c advice.detachedHead=false clone -q --filter=blob:none --no-checkout \
       --depth 200 -b "$branch" "https://github.com/azrabano23/$fork" "$tmp/f" 2>/dev/null \
     && git -C "$tmp/f" fetch -q --depth 200 --filter=blob:none \
       "https://github.com/$up" "$base" 2>/dev/null; then
    local mb; mb="$(git -C "$tmp/f" merge-base HEAD FETCH_HEAD 2>/dev/null)"
    if [ -n "$mb" ]; then
      local ahead; ahead="$(git -C "$tmp/f" rev-list --count "$mb"..HEAD)"
      echo "    commits ahead of $base: $ahead"
      # More than one commit usually means the fork base drifted or unrelated work
      # rode along; either way a maintainer sees a diff that is not just the fix.
      if [ "$ahead" -gt 1 ]; then
        echo "    REVIEW: $ahead commits -- rebase onto $base so the PR is only the fix"
      fi
      git -C "$tmp/f" diff --stat "$mb"..HEAD | tail -6 | sed "s/^/    /"
    else
      echo "    (no merge base within 200 commits -- rebase before sending)"
    fi
  fi
  rm -rf "$tmp"
  if [ "$SUBMIT" != 1 ]; then echo "    dry run; set SUBMIT=1 to open it"; echo; return 0; fi
  gh pr create --repo "$up" --base "$base" --head "azrabano23:$branch" \
    --title "$title" --body "$body" || echo "    gh pr create failed"
  echo
}

submit bt fix/rebalance-over-time-cash pmorissette/bt master 'Keep cash reserve across RebalanceOverTime steps' 'Keep cash reserve across RebalanceOverTime steps

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit exchange_calendars fix-xkrx-empty-observance gerrymanoim/exchange_calendars master 'Skip holiday observances when there are no dates' 'Skip holiday observances when there are no dates

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit linearmodels fix-631-f-pooled-robust bashtage/linearmodels main 'BUG: Do not report poolability F-test with robust covariance' 'BUG: Do not report poolability F-test with robust covariance

Fixes #631.

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit linearmodels fix-absorbing-refit-df bashtage/linearmodels main 'BUG: Stop AbsorbingLS.fit from accumulating df_model across calls' 'BUG: Stop AbsorbingLS.fit from accumulating df_model across calls

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit linearmodels fix-weighted-f-statistic bashtage/linearmodels main 'BUG: Fix model F-statistic in weighted panel models with a constant' 'BUG: Fix model F-statistic in weighted panel models with a constant

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit llama.cpp fix-28963-embd-mrope-pos ggml-org/llama.cpp master 'llama : size llama_batch_init pos for M-RoPE embd batches' 'llama : size llama_batch_init pos for M-RoPE embd batches

Fixes #28963.

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit mteb fix/pytrec-eval-min-version embeddings-benchmark/mteb main 'fix: require pytrec-eval-terrier>=0.5.8' 'fix: require pytrec-eval-terrier>=0.5.8

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit mujoco linesearch-cone-kinks google-deepmind/mujoco main 'Warn when a linesearch uses all ls_iterations.' 'Warn when a linesearch uses all ls_iterations.

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit nautilus_trader l2-array-ladder nautechsystems/nautilus_trader develop 'Add sorted array level storage for L2 order books' 'Add sorted array level storage for L2 order books

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit ompl fix-owen-root-finding-1362 ompl/ompl main 'OwenStateSpace: solve for the path per Dubins path type (#1362)' 'OwenStateSpace: solve for the path per Dubins path type (#1362)

Fixes #1362.

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit pandas_market_calendars fix-486-cme-carter-early-close rsheftel/pandas_market_calendars master 'CME: treat 2025-01-09 Carter day of mourning as an early close' 'CME: treat 2025-01-09 Carter day of mourning as an early close

Fixes #486.

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit pandas_market_calendars fix-ice-carter-2025 rsheftel/pandas_market_calendars master 'ICE: keep 2025-01-09 as a trading day' 'ICE: keep 2025-01-09 as a trading day

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit pytrec_eval fix-empty-qrels-c-state cvangysel/pytrec_eval master 'Fix garbage/stale scores for queries without judgments in the C extension' 'Fix garbage/stale scores for queries without judgments in the C extension

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit scikit-survival fix-428-uno-c-ties sebp/scikit-survival main 'Fix IPCW weights in concordance_index_ipcw when censoring times are tied with event times' 'Fix IPCW weights in concordance_index_ipcw when censoring times are tied with event times

Fixes #428.

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

submit trec_eval fix-form-res-rels-empty-qrels usnistgov/trec_eval main 'te_chk_and_malloc: return usable space for a request of 0 items' 'te_chk_and_malloc: return usable space for a request of 0 items

<!-- Check this project'"'"'s CONTRIBUTING before sending: changelog entry, test placement and commit style vary. -->'

