"""End-to-end LLM numbers: tokens/s and perplexity with each linear-layer backend.

Speed (batch 1, greedy): prefill of a 64-token prompt, 128 decode steps after
it, and a separate 512-token prefill (``pp512``, llama-bench's default), for
every backend and thread count. Each configuration is run ``reps`` times after
a warm-up; like ``lowbit.bench`` we wait for an idle machine first and re-run a
rep when other processes used more than ``max_other`` cores during it. The
wall time of every forward pass is split into linear layers, LM head,
attention (RoPE, KV-cache write, QK^T, softmax, PV) and "other" (embedding,
RMSNorm, SiLU, residual adds, python) by ``Model.prof``.

Quality: perplexity on the first ``n_tokens`` tokens of a fixed text sample
(the head of the WikiText-2 raw test split, committed in ``lowbit/data``), in
non-overlapping windows of ``ctx`` tokens, each scored from its second token
(so every scored token sees 1..ctx-1 tokens of context). Top-1 agreement is the
fraction of scored positions where a backend's argmax equals fp32's.
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
import platform
import time
import urllib.request
from importlib import resources
from pathlib import Path

import numpy as np

from . import bench as B
from . import model as M

BEGIN = "<!-- E2E:BEGIN (generated by `lowbit e2e` / `lowbit report --readme`; do not edit) -->"
END = "<!-- E2E:END -->"

EVAL_TEXT = "wikitext2_test_head.txt"
EVAL_TEXT_SHA256 = "9021a9ecfe7ea112497ce3930df75a7d594ab08f24153e1931f0978abcc34641"
EVAL_TEXT_SOURCE = ("first 181 lines (88,203 chars) of the WikiText-2 raw test split, "
                    "Salesforce/wikitext@b08601e0 wikitext-2-raw-v1/test-00000-of-00001.parquet "
                    "(sha256 5f1bea06...), lines joined as-is; CC BY-SA 3.0")

MODELS = {
    "Qwen2.5-0.5B": {
        "repo": "Qwen/Qwen2.5-0.5B",
        "revision": "060db6499f32faf8b98477b0a26969ef7d8b9987",
        "files": {
            "config.json": "479dcf0c5286339e41ad3992cd08ae88a467c4187587936248e2b7c96283484b",
            "tokenizer.json": "c0382117ea329cdf097041132f6d735924b697924d6f6fc3945713e96ce87539",
            "model.safetensors": "88c142557820ccad55bb59756bfcfcf891de9cc6202816bd346445188a0ed342",
        },
    },
}
DEFAULT_MODEL = "Qwen2.5-0.5B"
DEFAULT_CACHE = Path(os.environ.get("LOWBIT_MODEL_CACHE",
                                    Path.home() / ".cache" / "lowbit" / "models"))


# ---------------------------------------------------------------- inputs

def _sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fetch_model(name: str = DEFAULT_MODEL, cache_dir: Path | str = DEFAULT_CACHE,
                log=print) -> Path:
    """Download a pinned model revision from huggingface.co (sha256-checked)."""
    spec = MODELS[name]
    d = Path(cache_dir) / name
    d.mkdir(parents=True, exist_ok=True)
    for fn, sha in spec["files"].items():
        p = d / fn
        if p.exists() and _sha256(p) == sha:
            continue
        url = f"https://huggingface.co/{spec['repo']}/resolve/{spec['revision']}/{fn}"
        log(f"downloading {url}")
        tmp = p.with_suffix(p.suffix + ".part")
        with urllib.request.urlopen(url, timeout=60) as r, open(tmp, "wb") as f:
            while chunk := r.read(1 << 22):
                f.write(chunk)
        got = _sha256(tmp)
        if got != sha:
            tmp.unlink()
            raise RuntimeError(f"{fn}: sha256 {got} != pinned {sha}")
        os.replace(tmp, p)
    return d


def eval_text() -> str:
    raw = resources.files("lowbit").joinpath("data", EVAL_TEXT).read_bytes()
    if hashlib.sha256(raw).hexdigest() != EVAL_TEXT_SHA256:
        raise RuntimeError(f"{EVAL_TEXT} does not match its pinned sha256")
    return raw.decode("utf-8")


# ---------------------------------------------------------------- speed

def _split(prof: dict, total: float) -> dict:
    lin, head, att = prof.get("linear", 0.0), prof.get("lm_head", 0.0), prof.get("attention", 0.0)
    return {"linear": lin, "lm_head": head, "attention": att,
            "other": max(0.0, total - lin - head - att), "total": total}


def _one_run(model: M.Model, prompt, n_decode: int, pp: int, rng_tokens) -> dict:
    P = model.prof
    cache = model.new_cache(len(prompt) + n_decode)
    P.reset()
    t0 = time.perf_counter()
    logit = model.forward(prompt, cache)
    t1 = time.perf_counter()
    prof_prefill = dict(P.t)
    P.reset()
    out = [int(np.argmax(logit))]
    t2 = time.perf_counter()
    for _ in range(n_decode):
        out.append(int(np.argmax(model.forward([out[-1]], cache))))
    t3 = time.perf_counter()
    prof_decode = dict(P.t)
    r = {"prefill_s": t1 - t0, "decode_s": t3 - t2, "tokens": out,
         "prof_prefill": _split(prof_prefill, t1 - t0),
         "prof_decode": _split(prof_decode, t3 - t2)}
    if pp:
        P.reset()
        t4 = time.perf_counter()
        model.forward(rng_tokens[:pp], model.new_cache(pp))
        t5 = time.perf_counter()
        r["pp_s"] = t5 - t4
        r["prof_pp"] = _split(dict(P.t), t5 - t4)
    return r


def _measured_run(model, args, idle_threshold, idle_timeout, max_other, retries, log) -> dict:
    """One run; re-run (after waiting for quiet) when other processes were busy."""
    best = None
    for attempt in range(1, retries + 1):
        b0, s0, w0 = B._busy_s(), B._self_s(), time.perf_counter()
        r = _one_run(model, *args)
        b1, s1, w1 = B._busy_s(), B._self_s(), time.perf_counter()
        other = max(0.0, ((b1 - b0) - (s1 - s0)) / max(1e-9, w1 - w0))
        r["other_tenant_cores"], r["attempts"] = round(other, 3), attempt
        if best is None or other < best["other_tenant_cores"]:
            best = r
        if other <= max_other or not idle_threshold:
            break
        log(f"    other tenants used {other:.2f} cores during the run; retrying")
        B.wait_idle(idle_threshold, idle_timeout, log)
    return best


def speed(models: dict, prompt, threads_list, n_decode: int = 128, pp: int = 512,
          reps: int = 5, idle_threshold: float = 0.0, idle_timeout: float = 600.0,
          max_other: float = 0.25, retries: int = 4, pp_tokens=None, log=print) -> list[dict]:
    """Speed of several models ({name: Model}), interleaved: every rep runs each
    model once, so a slow period on the shared machine hits all of them alike."""
    rows = []
    pp_tokens = list(pp_tokens if pp_tokens is not None else prompt)
    while pp and len(pp_tokens) < pp:
        pp_tokens += pp_tokens
    args = (prompt, n_decode, pp, pp_tokens)
    for th in threads_list:
        for model in models.values():
            model.set_threads(th)
            _one_run(model, prompt[:8], 4, min(pp, 32), pp_tokens)  # warm-up
        runs = {name: [] for name in models}
        for rep in range(reps):
            if idle_threshold:
                B.wait_idle(idle_threshold, idle_timeout, log)
            for name, model in models.items():
                runs[name].append(_measured_run(model, args, idle_threshold, idle_timeout,
                                                max_other, retries, log))
        for name, model in models.items():
            rows.append(_speed_row(name, model, th, runs[name], prompt, n_decode, pp, log))
    return rows


def _speed_row(name, model, th, runs, prompt, n_decode, pp, log) -> dict:
    med = lambda k: float(np.median([r[k] for r in runs]))  # noqa: E731

    def frac(key):
        tot = {c: sum(r[key][c] for r in runs) for c in runs[0][key]}
        return {c: round(v / tot["total"], 4) for c, v in tot.items() if c != "total"}

    dec = [n_decode / r["decode_s"] for r in runs]
    row = {
        "backend": name, "threads": th, "reps": len(runs),
        "prompt_tokens": len(prompt), "decode_tokens": n_decode, "pp_tokens": pp,
        "prefill_s": med("prefill_s"), "decode_s": med("decode_s"),
        "prefill_tok_s": len(prompt) / med("prefill_s"),
        "decode_tok_s": n_decode / med("decode_s"),
        "decode_tok_s_range": [round(min(dec), 2), round(max(dec), 2)],
        "decode_ms_per_token": med("decode_s") / n_decode * 1e3,
        "breakdown_decode": frac("prof_decode"), "breakdown_prefill": frac("prof_prefill"),
        "other_tenant_cores": [r["other_tenant_cores"] for r in runs],
        "attempts": [r["attempts"] for r in runs],
        "linear_weight_bytes": model.linear_weight_bytes,
        "tokens": runs[0]["tokens"],
    }
    if pp:
        row["pp_s"] = med("pp_s")
        row["pp_tok_s"] = pp / med("pp_s")
        row["breakdown_pp"] = frac("prof_pp")
    log(f"  [{name} t={th}] prefill {row['prefill_tok_s']:7.1f} tok/s  "
        f"decode {row['decode_tok_s']:6.2f} tok/s {row['decode_tok_s_range']}  "
        + (f"pp{pp} {row['pp_tok_s']:7.1f} tok/s  " if pp else "")
        + f"decode linear+head "
        f"{row['breakdown_decode']['linear'] + row['breakdown_decode']['lm_head']:.0%}  "
        f"other cores {row['other_tenant_cores']}")
    return row


# ---------------------------------------------------------------- quality

def log_softmax_nll(logits: np.ndarray, targets: np.ndarray) -> np.ndarray:
    lg = logits.astype(np.float64)
    mx = lg.max(axis=1)
    lse = np.log(np.exp(lg - mx[:, None]).sum(axis=1)) + mx
    return lse - lg[np.arange(len(targets)), targets]


def quality(model: M.Model, ids, ctx: int = 1024, n_tokens: int = 20480) -> dict:
    ids = np.asarray(ids[:n_tokens], np.int64)
    nll, top1 = [], []
    t0 = time.perf_counter()
    for s in range(0, len(ids) - 1, ctx):
        w = ids[s:s + ctx]
        if len(w) < 2:
            break
        lg = model.forward(w, logits="all")[:-1]
        nll.append(log_softmax_nll(lg, w[1:]))
        top1.append(lg.argmax(axis=1))
    nll_a = np.concatenate(nll)
    return {"backend": model.backend, "ctx": ctx, "tokens_scored": int(nll_a.size),
            "ppl": float(np.exp(nll_a.mean())), "mean_nll": float(nll_a.mean()),
            "wall_s": round(time.perf_counter() - t0, 1),
            "_top1": np.concatenate(top1)}


# ---------------------------------------------------------------- driver

def parse_backend(spec: str) -> dict:
    """'w4a16', 'w4a16+asym', 'w4a8+fp32head', ... -> Model keyword arguments.

    +asym     asymmetric int4 (uint8 zero-point) instead of symmetric absmax/7
    +smax     symmetric int4 with a signed-max scale (m / -8, ggml Q4_0's rule)
    +fp32head keep the LM head in fp32 (all other linears use the backend)
    """
    name, *opts = spec.split("+")
    if name not in M.BACKENDS or any(o not in ("asym", "smax", "fp32head") for o in opts):
        raise ValueError(f"bad backend spec {spec!r}")
    if name in ("fp32", "mxfp4") and ("asym" in opts or "smax" in opts):
        raise ValueError(f"{spec!r}: +asym/+smax only apply to the int4 backends")
    if "asym" in opts and "smax" in opts:
        raise ValueError(f"{spec!r}: +asym and +smax are exclusive")
    return {"backend": name, "asym": "asym" in opts, "quantize_lm_head": "fp32head" not in opts,
            "int4_scale": "signed-max" if "smax" in opts else "absmax"}


def run(model_dir=None, backends=M.BACKENDS, threads_list=(1, 4), do_speed=True,
        do_quality=True, n_decode=128, prompt_tokens=64, pp=512, reps=5, ctx=1024,
        n_tokens=20480, idle_threshold=0.0, max_other=0.25, asym=False, tiny=False,
        log=print) -> dict:
    """Load each backend once (quantizing at load), then measure speed and quality."""
    from . import kernels as K
    from . import tune as T
    if tiny:
        cfg = M.tiny_config(vocab_size=512, max_position=1024)
        W = M.random_weights(cfg)
        rng = np.random.default_rng(0)
        ids = rng.integers(0, cfg.vocab_size, n_tokens + 1).tolist()
        tok, model_name = None, "tiny-random"
    else:
        model_dir = Path(model_dir)
        cfg = M.ModelConfig.from_hf(json.loads((model_dir / "config.json").read_text()),
                                    name=model_dir.name)
        W = {}
        for f in sorted(model_dir.glob("*.safetensors")):
            W.update(M.load_safetensors(f))
        tok = M.load_tokenizer(model_dir)
        ids = tok.encode(eval_text()).ids
        model_name = model_dir.name
    prompt = ids[:prompt_tokens]
    speed_rows, qual_rows = [], []
    fp32_top1 = None
    t_start, load0 = time.time(), os.getloadavg()
    models = {}
    for be in backends:
        t0 = time.perf_counter()
        kw = parse_backend(be)
        if asym and kw["backend"] in ("w4a16", "w4a8") and kw["int4_scale"] == "absmax":
            kw["asym"] = True  # --asym: every int4 backend asymmetric
        model = M.Model(cfg, W, threads=max(threads_list), **kw)
        load_s = time.perf_counter() - t0
        log(f"== {be}: built in {load_s:.1f} s (incl. quantization), linear weights "
            f"{model.linear_weight_bytes / 2**20:.0f} MiB")
        if do_quality:
            model.set_threads(max(threads_list))
            q = quality(model, ids, ctx=ctx, n_tokens=n_tokens)
            top1 = q.pop("_top1")
            q["backend"] = be
            if be == "fp32":
                fp32_top1 = top1
            q["top1_agree_fp32"] = (None if fp32_top1 is None
                                    else float(np.mean(top1 == fp32_top1)))
            q["load_s"] = round(load_s, 1)
            qual_rows.append(q)
            log(f"  PPL {q['ppl']:.3f} over {q['tokens_scored']} tokens (ctx {ctx}), "
                f"top-1 agreement with fp32 {q['top1_agree_fp32']}, {q['wall_s']} s")
        if do_speed:
            models[be] = model
        del model
    if do_speed:
        speed_rows = speed(models, prompt, threads_list, n_decode=n_decode, pp=pp, reps=reps,
                           idle_threshold=idle_threshold, max_other=max_other,
                           pp_tokens=ids[prompt_tokens:], log=log)
        ref = next((r["tokens"] for r in speed_rows if r["backend"] == "fp32"), None)
        for r in speed_rows:
            toks = r.pop("tokens")
            if r["backend"] == "fp32" and r["threads"] == threads_list[0]:
                r["text"] = tok.decode(toks) if tok else None  # the greedy continuation
            if ref is not None:
                r["greedy_same_as_fp32"] = sum(a == b for a, b in zip(toks, ref))
                r["greedy_first_divergence"] = next(
                    (i for i, (a, b) in enumerate(zip(toks, ref)) if a != b), len(toks))
            r["generated_tokens"] = len(toks)
        models.clear()
    info = K.cpu_info()
    meta = {
        "date": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
        "cpu": T.cpu_key(), "lowbit": info, "numpy": np.__version__, "blas": B._blas_info(),
        "python": platform.python_version(),
        "effective_isa": {k: K.effective_isa(k) for k in K.KIND_IDS},
        "model": model_name,
        "model_source": (f"{MODELS[model_name]['repo']}@{MODELS[model_name]['revision']}"
                         if model_name in MODELS else model_name),
        "config": {k: getattr(cfg, k) for k in ("hidden_size", "intermediate_size",
                                                   "num_layers", "num_heads", "num_kv_heads",
                                                   "head_dim", "vocab_size",
                                                   "tie_word_embeddings")},
        "int4": "symmetric" if not asym else "asymmetric (uint8 zero-point)",
        "lm_head": "quantized with the backend (tied embedding table kept fp32 for lookup)",
        "eval_text": EVAL_TEXT_SOURCE if not tiny else "random token ids",
        "loadavg_start": load0, "loadavg_end": os.getloadavg(),
        "wall_s": round(time.time() - t_start, 1),
        "contention_control": (f"wait for >= {idle_threshold:.0%} idle CPU before each "
                               f"round of reps (each round runs every backend once, "
                               f"interleaved); re-run a run (up to 4x) when other "
                               f"processes used > {max_other} cores during it")
        if idle_threshold else "none",
    }
    return {"meta": meta, "speed": speed_rows, "quality": qual_rows}


def merge(old: dict, new: dict, speed: bool, quality: bool) -> dict:
    """Combine a speed-only or quality-only run with an earlier results file.

    Speed and quality need different conditions (speed an idle machine, quality
    only time), so they can be measured separately; each keeps its own date.
    """
    if old["meta"]["model"] != new["meta"]["model"]:
        raise SystemExit("refusing to merge results of different models")
    qrows = {r["backend"]: r for r in old["quality"]}
    if quality:  # per backend: newly measured rows replace old ones, others are kept
        qrows.update({r["backend"]: r for r in new["quality"]})
    out = {"meta": dict(new["meta"] if speed else old["meta"]),
           "speed": new["speed"] if speed else old["speed"],
           "quality": sorted(qrows.values(), key=lambda r: _spec_order(r["backend"]))}
    q_meta = new["meta"] if quality else old["meta"]
    out["meta"]["quality_date"] = q_meta.get("quality_date", q_meta["date"])
    out["meta"]["int4"] = q_meta["int4"]
    return out


def _spec_order(spec: str):
    name, *opts = spec.split("+")
    return (len(opts) > 0, M.BACKENDS.index(name), opts)


def save(res: dict, out_dir: Path | str) -> Path:
    p = Path(out_dir) / "e2e.json"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(res, indent=1) + "\n")
    return p


# ---------------------------------------------------------------- report

def _pct(v) -> str:
    return f"{v * 100:.0f} %"


def render(res: dict, validation: dict | None = None, llama: dict | None = None) -> str:
    meta, sp, ql = res["meta"], res["speed"], res["quality"]
    c = meta["config"]
    out = [f"**Model:** {meta['model']} (`{meta['model_source']}`), {c['num_layers']} layers, "
           f"hidden {c['hidden_size']}, MLP {c['intermediate_size']}, {c['num_heads']} query / "
           f"{c['num_kv_heads']} KV heads, vocab {c['vocab_size']}"
           f"{', tied embeddings' if c['tie_word_embeddings'] else ''}. All linear layers "
           f"including the LM head use the backend; int4 is {meta['int4']}, group 128; "
           f"MXFP4 block 32. Weights are quantized once at load, round-to-nearest.", ""]
    if sp:
        threads = sorted({r["threads"] for r in sp})
        pp = sp[0].get("pp_tokens")
        out.append(f"**Speed, batch 1** — tokens/s, median of {sp[0]['reps']} runs (decode: "
                   f"min–max over the runs in brackets; backends interleaved run by run): prefill of "
                   f"the {sp[0]['prompt_tokens']}-token prompt, {sp[0]['decode_tokens']} greedy "
                   f"decode steps after it"
                   + (f", and a separate {pp}-token prefill (pp{pp})" if pp else "") + ":\n")
        head = "| backend | linear weights |"
        for t in threads:
            head += f" prefill {t}T | decode {t}T |" + (f" pp{pp} {t}T |" if pp else "")
        head += f" decode vs fp32 ({' / '.join(f'{t}T' for t in threads)}) |"
        ncol = 2 + len(threads) * (3 if pp else 2) + 1
        out += [head, "|" + "---|" * ncol]
        base = {r["threads"]: r for r in sp if r["backend"] == "fp32"}
        for be in dict.fromkeys(r["backend"] for r in sp):
            cells, wb, sx = [], None, []
            for t in threads:
                r = next((r for r in sp if r["backend"] == be and r["threads"] == t), None)
                if r is None:
                    cells.append(" — | — |" + (" — |" if pp else ""))
                    continue
                wb = r["linear_weight_bytes"]
                rg = r.get("decode_tok_s_range")
                rg = f" ({rg[0]:.1f}–{rg[1]:.1f})" if rg else ""
                cells.append(f" {r['prefill_tok_s']:.1f} | {r['decode_tok_s']:.2f}{rg} |"
                             + (f" {r['pp_tok_s']:.1f} |" if pp else ""))
                if t in base:
                    sx.append(f"{r['decode_tok_s'] / base[t]['decode_tok_s']:.2f}×")
            out.append(f"| {be} | {wb / 2**20:.0f} MiB |" + "".join(cells) + f" {' / '.join(sx)} |")
        out.append("")
        out.append("**Where decode time goes** (share of wall time per decode step, all reps):\n")
        out += ["| backend | threads | ms / token | linear layers | LM head | attention | "
                "other numpy + python |", "|---|---|---|---|---|---|---|"]
        for r in sp:
            b = r["breakdown_decode"]
            out.append(f"| {r['backend']} | {r['threads']} | {r['decode_ms_per_token']:.1f} | "
                       f"{_pct(b['linear'])} | {_pct(b['lm_head'])} | {_pct(b['attention'])} | "
                       f"{_pct(b['other'])} |")
        out.append("")
        if pp:
            out.append(f"Prefill (pp{pp}) split: " + "; ".join(
                f"{r['backend']} {r['threads']}T linear+head "
                f"{_pct(r['breakdown_pp']['linear'] + r['breakdown_pp']['lm_head'])}, "
                f"attention {_pct(r['breakdown_pp']['attention'])}"
                for r in sp) + ".\n")
    if ql:
        q0 = ql[0]
        src = ("the committed WikiText-2 test excerpt" if meta["eval_text"] == EVAL_TEXT_SOURCE
               else meta["eval_text"])
        out.append(f"**Quality** — perplexity on {q0['tokens_scored']} scored tokens of "
                   f"{src}, non-overlapping {q0['ctx']}-token "
                   f"windows; top-1 agreement = fraction of positions whose argmax equals "
                   f"fp32's; greedy = identical tokens out of the "
                   + (f"{sp[0]['generated_tokens']} " if sp else "")
                   + "generated in the speed run (first divergence in brackets):\n")
        out += ["| backend | PPL | ΔPPL vs fp32 | top-1 agreement with fp32 | greedy "
                "continuation = fp32 |", "|---|---|---|---|---|"]
        p0 = next((q["ppl"] for q in ql if q["backend"] == "fp32"), None)
        for q in ql:
            g = next((r for r in sp if r["backend"] == q["backend"]), None)
            gs = (f"{g['greedy_same_as_fp32']}/{g['generated_tokens']} "
                  f"(@{g['greedy_first_divergence']})") if g and "greedy_same_as_fp32" in g else "—"
            dp = "—" if p0 is None or q["backend"] == "fp32" else f"{q['ppl'] - p0:+.3f}"
            ag = "—" if q["top1_agree_fp32"] is None or q["backend"] == "fp32" else \
                f"{q['top1_agree_fp32'] * 100:.1f} %"
            out.append(f"| {q['backend']} | {q['ppl']:.3f} | {dp} | {ag} | {gs} |")
        out.append("")
        if any("+" in q["backend"] for q in ql):
            out.append("Ablations (quality only; same kernels, different quantizer "
                       "settings): `+asym` = asymmetric int4 with a uint8 zero-point per group; "
                       "`+smax` = symmetric int4 with a signed-max scale (the group's "
                       "largest-magnitude weight maps exactly to −8, as in ggml's Q4_0, so all "
                       "16 levels are used instead of absmax/7's 15); `+fp32head` = LM head "
                       "left in fp32, every other linear layer quantized.\n")
    if validation:
        v = validation
        out.append(f"**fp32 path validated** against {v['reference']} on {v['tokens']} tokens: "
                   f"max |Δlogit| {v['logits_max_abs_diff']:.2e} (logits up to "
                   f"{v['logits_max_abs']:.1f}, relative {v['logits_max_rel_diff']:.1e}), "
                   f"argmax agreement {v['argmax_agreement'] * 100:.1f} %, mean NLL "
                   f"{v['mean_nll_ours']:.5f} vs {v['mean_nll_ref']:.5f}; greedy decode "
                   f"identical for {v['greedy_identical_prefix']}/{v['greedy_tokens']} tokens "
                   f"(`scripts/validate_hf.py`).\n")
    if llama:
        out.append(render_llama(llama))
        out.append("")
    qd = meta.get("quality_date")
    out.append(f"Measured {meta['date']}"
               + (f" (last perplexity run {qd})" if qd and qd != meta["date"] else "")
               + f" on `{meta['cpu']}` (kernels: "
               + ", ".join(f"{k} {v}" for k, v in meta["effective_isa"].items())
               + f"), numpy {meta['numpy']} with {meta['blas']}. Load average at start/end: "
               f"{meta['loadavg_start'][0]:.2f}/{meta['loadavg_end'][0]:.2f}. Contention "
               f"control: {meta['contention_control']}. Other tenants' CPU use during each "
               f"rep is in `results/e2e.json` (`other_tenant_cores`).")
    return "\n".join(out)


def render_llama(d: dict) -> str:
    m = d["meta"]
    out = [f"**vs llama.cpp `llama-bench`** on the same model ({m['gguf']}), tokens/s:\n",
           "| implementation | weights | threads | " + " | ".join(m["tests"]) + " |",
           "|---|---|---|" + "---|" * len(m["tests"])]
    for r in d["rows"]:
        out.append(f"| {r['impl']} | {r['type']} | {r['threads']} | "
                   + " | ".join(f"{r[t]:.1f}" if r.get(t) is not None else "—"
                                for t in m["tests"]) + " |")
    out += ["", m["note"]]
    ppl = d.get("perplexity")
    if ppl:
        c = next(iter(ppl.values()))
        out += ["", f"llama.cpp's own `llama-perplexity -c {c['ctx']}` on the same text "
                f"(it scores only the second half of each window, so the absolute values "
                f"are not comparable with ours, only the fp32 → 4-bit ratio): "
                + ", ".join(f"{k} {v['ppl']:.3f} ± {v['stderr']:.3f}" for k, v in ppl.items())
                + "."]
    return "\n".join(out)


def readme_block(results_dir: Path | str) -> str:
    rd = Path(results_dir)
    res = json.loads((rd / "e2e.json").read_text())
    vp, lp = rd / "e2e_validation.json", rd / "e2e_llamacpp.json"
    return render(res, json.loads(vp.read_text()) if vp.exists() else None,
                  json.loads(lp.read_text()) if lp.exists() else None)


def write_readme(results_dir: Path | str, readme: Path | str) -> Path | None:
    rp = Path(readme)
    text = rp.read_text()
    if BEGIN not in text or END not in text or not (Path(results_dir) / "e2e.json").exists():
        return None
    pre, rest = text.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    rp.write_text(pre + BEGIN + "\n" + readme_block(results_dir) + "\n" + END + post)
    return rp
