"""Render results/bench.json into markdown (results/RESULTS.md and the README block)."""
from __future__ import annotations

import json
from pathlib import Path

BEGIN = "<!-- RESULTS:BEGIN (generated by `lowbit report --readme README.md`; do not edit) -->"
END = "<!-- RESULTS:END -->"
HEADLINE_SHAPE = (1, 11008, 4096)


def _fmt_t(s: float) -> str:
    return f"{s * 1e6:.0f} µs" if s < 1e-2 else f"{s * 1e3:.1f} ms"


def _x(v) -> str:
    return "—" if v is None else f"{v:.2f}×"


def _best(rows, fmt, exclude=("scalar", "numpy"), **kv):
    """Fastest SIMD row for a format under the given filters."""
    c = [r for r in rows if r["format"] == fmt and r["isa"] not in exclude
         and all(r[k] == v for k, v in kv.items())]
    return min(c, key=lambda r: r["t_median_s"]) if c else None


def _get(rows, method, **kv):
    for r in rows:
        if r["method"] == method and all(r[k] == v for k, v in kv.items()):
            return r
    return None


def meta_line(meta: dict) -> str:
    lb = meta["lowbit"]
    return (f"Measured {meta['date']} on `{meta['cpu']}` (ISA `{lb['cpu_isa']}`, VNNI "
            f"{'yes' if lb['vnni'] else 'no'}, LLC {meta['llc_bytes'] >> 20} MiB), numpy "
            f"{meta['numpy']} with {meta['blas']}. {meta['timing']}. "
            f"Load average at start/end: {meta['loadavg_start'][0]:.2f}/"
            f"{meta['loadavg_end'][0]:.2f}. Contention control: "
            f"{meta.get('contention_control', 'none')}.")


def headline(res: dict) -> str:
    rows, meta = res["rows"], res["meta"]
    m, n, k = HEADLINE_SHAPE
    threads = sorted({r["threads"] for r in rows})
    out = []
    sel = [r for r in rows if (r["M"], r["N"], r["K"]) == HEADLINE_SHAPE]
    if sel:
        cache = "cold" if any(r["cache"] == "cold" for r in sel) else "hot"
        out.append(f"**Decode, M={m}, N={n}, K={k} (LLaMA-7B MLP up-projection), {cache} "
                   f"cache** — weights streamed from DRAM every call:\n")
        head = "| method | weight bytes |" + "".join(
            f" {t}T time | {t}T weight GB/s | {t}T vs numpy fp32 |" for t in threads)
        out += [head, "|" + "---|" * (2 + 3 * len(threads))]
        methods = []
        for r in sel:
            if r["cache"] == cache and r["method"] not in methods:
                methods.append(r["method"])
        for meth in methods:
            cells = []
            wb = None
            for t in threads:
                r = _get(sel, meth, threads=t, cache=cache)
                if r is None:
                    cells.append(" — | — | — |")
                    continue
                wb = r["weight_bytes"]
                cells.append(f" {_fmt_t(r['t_median_s'])} | {r['weight_gbps']:.1f} | "
                             f"{_x(r['speedup_vs_numpy_fp32'])} |")
            out.append(f"| {meth} | {wb / 2**20:.1f} MiB |" + "".join(cells))
        out.append("")
    for t in threads:
        out.append(f"**All shapes, {t} thread{'s' if t > 1 else ''}, hot cache** — GFLOP/s "
                   f"(speedup vs numpy fp32 on pre-dequantized weights):\n")
        out += ["| M | N | K | numpy fp32 | numpy deq+mm int4 | W4A16 scalar C | W4A16 (best SIMD) | W4A8 (AVX-512 VNNI) | "
                "W4A8 (AMX) | MXFP4 (best SIMD) |", "|---|---|---|---|---|---|---|---|---|---|"]
        shapes = []
        for r in rows:
            s = (r["M"], r["N"], r["K"])
            if s not in shapes:
                shapes.append(s)
        for s in shapes:
            kv = dict(M=s[0], N=s[1], K=s[2], threads=t, cache="hot")
            base = _get(rows, "numpy fp32", **kv)
            naive = _get(rows, "numpy deq+mm w4a16", **kv)
            sc = _get(rows, "w4a16 scalar", **kv)
            cells = [f"{base['gflops']:.1f}" if base else "—",
                     f"{naive['gflops']:.1f} ({_x(naive['speedup_vs_numpy_fp32'])})" if naive else "—",
                     f"{sc['gflops']:.1f} ({_x(sc['speedup_vs_numpy_fp32'])})" if sc else "—"]
            for fmt, excl in (("w4a16", ("scalar", "numpy")),
                              ("w4a8", ("scalar", "numpy", "amx", "avx2")),
                              ("w4a8", ("scalar", "numpy", "avx2", "avx512")),
                              ("mxfp4", ("scalar", "numpy"))):
                b = _best(rows, fmt, exclude=excl, **kv)
                cells.append(f"{b['gflops']:.1f} ({_x(b['speedup_vs_numpy_fp32'])})" if b else "—")
            out.append(f"| {s[0]} | {s[1]} | {s[2]} | " + " | ".join(cells) + " |")
        out.append("")
    out.append(meta_line(meta))
    return "\n".join(out)


def llama_table(data: dict) -> str:
    rows = data["rows"]
    out = ["**vs llama.cpp (ggml CPU backend), N=4096, K=14336, hot cache** — GFLOP/s "
           "(time per call):\n"]
    threads = sorted({r["threads"] for r in rows})
    ms = sorted({r["M"] for r in rows})
    order = []
    for r in rows:
        key_ = (r["impl"], r["type"])
        if key_ not in order:
            order.append(key_)
    head = "| implementation | weights |" + "".join(f" M={m}, {t}T |" for t in threads for m in ms)
    out += [head, "|---|---|" + "---|" * (len(threads) * len(ms))]
    for impl, typ in order:
        cells = []
        for t in threads:
            for m in ms:
                r = next((r for r in rows if (r["impl"], r["type"], r["threads"], r["M"]) ==
                          (impl, typ, t, m)), None)
                cells.append(f" {r['gflops']:.1f} ({_fmt_t(r['t_s'])}) |" if r else " — |")
        out.append(f"| {impl} | {typ} |" + "".join(cells))
    meta = data["meta"]
    out += ["", f"llama.cpp commit `{meta.get('llama_cpp_commit') or 'unknown'}`, measured "
            f"{meta['date']} with {meta['ggml_bench']}. {meta['note']}"]
    return "\n".join(out)


def readme_block(results_dir: Path | str) -> str:
    rd = Path(results_dir)
    block = headline(json.loads((rd / "bench.json").read_text()))
    lc = rd / "llamacpp.json"
    if lc.exists():
        block += "\n\n" + llama_table(json.loads(lc.read_text()))
    return block


def full(res: dict, tune_cache: dict | None = None, llama: dict | None = None) -> str:
    rows, meta = res["rows"], res["meta"]
    out = ["# lowbit benchmark results", "",
           "Generated from `results/bench.json` by `lowbit report`. Do not edit by hand.", "",
           meta_line(meta), "",
           "Columns: median wall time per call; GFLOP/s = 2·M·N·K / time; weight GB/s = bytes of "
           "the weight format (packed codes + scales) / time; speedup is against `numpy fp32` "
           "(x @ W.T on pre-dequantized fp32 weights) at the same thread count and cache mode. "
           "`max rel err` is max|y - y_ref| / max|y_ref| against a float64 reference on the "
           "dequantized weights (W4A8 includes int8 activation quantization error).", "",
           "## Headline", "", headline(res), ""]
    if llama:
        out += ["## llama.cpp comparison", "", llama_table(llama), ""]
    groups = []
    for r in rows:
        g = (r["M"], r["N"], r["K"], r["cache"], r["threads"])
        if g not in groups:
            groups.append(g)
    out.append("## All measurements\n")
    for g in groups:
        m, n, k, cache, t = g
        out.append(f"### M={m} N={n} K={k} — {cache} cache, {t} thread{'s' if t > 1 else ''}\n")
        out.append("| method | time | GFLOP/s | weight MiB | weight GB/s | vs numpy fp32 | max rel err | tile params |")
        out.append("|---|---|---|---|---|---|---|---|")
        for r in rows:
            if (r["M"], r["N"], r["K"], r["cache"], r["threads"]) != g:
                continue
            p = r.get("params")
            ps = (f"mr{p['mr']} nr{p['nr']} nb{p['nb']} kb{p['kb']} o{p['order']}"
                  if p else "")
            err = r.get("max_rel_err")
            out.append(f"| {r['method']} | {_fmt_t(r['t_median_s'])} | {r['gflops']:.1f} | "
                       f"{r['weight_bytes'] / 2**20:.1f} | {r['weight_gbps']:.1f} | "
                       f"{_x(r['speedup_vs_numpy_fp32'])} | "
                       f"{'' if err is None else f'{err:.1e}'} | {ps} |")
        out.append("")
    if tune_cache and tune_cache.get("entries"):
        out += ["## Autotuner", "",
                "Best tile parameters found per (kernel, ISA, threads, shape), and the gain over "
                "the library default (mr=4 or 1, nr=2, nb=64, whole K, order 0).", "",
                "| key | params | configs tried | tuned GFLOP/s | gain vs default |",
                "|---|---|---|---|---|"]
        for key_, e in sorted(tune_cache["entries"].items()):
            p = e["params"]
            out.append(f"| `{key_}` | mr{p['mr']} nr{p['nr']} nb{p['nb']} kb{p['kb']} "
                       f"o{p['order']} | {e['n_configs']} | {e['gflops']:.1f} | "
                       f"{e['default_time_s'] / e['time_s']:.2f}× |")
        out.append("")
    return "\n".join(out)


def write(results_dir: Path | str, readme: Path | str | None = None) -> list[Path]:
    rd = Path(results_dir)
    res = json.loads((rd / "bench.json").read_text())
    tc = rd / "tune_cache.json"
    tune_cache = json.loads(tc.read_text()) if tc.exists() else None
    lc = rd / "llamacpp.json"
    llama = json.loads(lc.read_text()) if lc.exists() else None
    md = rd / "RESULTS.md"
    md.write_text(full(res, tune_cache, llama))
    written = [md]
    if readme:
        rp = Path(readme)
        text = rp.read_text()
        if BEGIN not in text or END not in text:
            raise SystemExit(f"{rp} has no results markers")
        pre, rest = text.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        rp.write_text(pre + BEGIN + "\n" + readme_block(rd) + "\n" + END + post)
        written.append(rp)
    return written
