"""Regenerate results/REPORT.md from the ledger. Claims are written by hand."""

from pathlib import Path

import numpy as np

from loopgraph import Ledger, Objective, pareto_front
from loopgraph.report import table

R = Path(__file__).resolve().parents[1] / "results"
L = Ledger(R / "ledger.jsonl")

within = L.latest("within")
comp = L.entries("compare")
design = L.entries("design")
front = sorted(pareto_front(design, [Objective("acc_p10"), Objective("latency_ms", False)]),
               key=lambda e: e.metrics["latency_ms"])

out = ["# myoedge results", "", "Generated by `scripts/report.py` from `ledger.jsonl`.", "",
       "21 subjects, CIIL ElectrodeShift (Myo, 8 ch, 200 Hz). Trained on five pre-shift "
       "repetitions, tested on four post-shift sessions. The calibration fist is excluded from "
       "testing for every method. All accuracies go through the int8 decoder and its majority "
       "vote. p10 is the 10th-percentile subject: the user the device serves worst, give or "
       "take one.", "",
       f"No shift (repetitions 0-3 -> 4, LDA): mean **{within.metrics['acc_within']:.3f}**, "
       f"p10 {within.metrics['acc_p10']:.3f}, worst {within.metrics['acc_min']:.3f}.", "",
       "## After the shift", "",
       table(comp, ["classifier", "aug", "recal"],
             ["acc_shift", "acc_p10", "acc_min", "flash_b", "ram_b", "latency_ms", "bit_exact"],
             ["classifier", "rotation aug (ch)", "one-fist recal", "mean", "p10", "worst",
              "weights B", "RAM B", "delay ms", "bit-exact"]), "",
       "## Agent-searched designs: Pareto frontier of p10 accuracy vs decision delay", "",
       f"{len(design)} designs proposed by "
       + ", ".join(f"{k} {sum(e.decided_by == k for e in design)}"
                   for k in sorted({e.decided_by for e in design}))
       + f"; {sum(e.admitted for e in design)} passed every gate "
       "(delay <= 300 ms, ATmega32U4 flash and RAM, bit-exact C).", "",
       table(front, ["window", "vote", "classifier", "aug", "recal"],
             ["acc_p10", "acc_shift", "acc_min", "latency_ms", "flash_b"],
             ["window", "vote", "classifier", "aug", "recal", "p10", "mean", "worst", "delay ms",
              "weights B"])]
best = max(comp, key=lambda e: e.metrics["acc_shift"])
base = next(e for e in comp if e.params == {"classifier": "lda", "aug": 0.0, "recal": 0})
ps_b = np.array(list(base.metrics["per_subject"].values()))
ps_c = np.array(list(next(e for e in comp if e.params == {"classifier": "lda", "aug": 0.0, "recal": 1})
                     .metrics["per_subject"].values()))
out += ["", "## Per subject: LDA baseline vs one-fist recalibration", "",
        f"Recalibration helped {int(np.sum(ps_c > ps_b))} of {len(ps_b)} subjects; "
        f"median gain {np.median(ps_c - ps_b):+.3f}.", ""]
(R / "REPORT.md").write_text("\n".join(out) + "\n")
print((R / "REPORT.md").read_text())
